os:
  - linux
services:
  - docker
before-install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - TF_VERSION=0.14.7
  
install:
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - terraform init

script:
  - docker build --target test -t test .
  - docker run -e TRELLO_BOARD -e SECRET_KEY -e FLASK_APP='todo_app/app' -e FLASK_ENV='development' -e FLASK_SKIP_DOTENV='True' -e MONGO_CONNECTION_STRING -e LOGIN_DISABLED="True" test
 
after_success:
  - docker build --target prod -t $DOCKER_USERNAME/todo-app:latest .
  - docker push $DOCKER_USERNAME/todo-app:latest

before_deploy:
  - terraform init
  - terraform apply -var="APP-PREFIX=$PRODUCTION_ENV_PREFIX" -var="CLIENTID=$CLIENT_ID" -var="CLIENTSECRET=$CLIENTSECRET"  -auto-approve
  
deploy:
    provider: script
    script: terraform_deploy.sh
    on:
        all_branches: true
